addpath("utils");

N=30;

configs = {
    struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','trainlm', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000), 

    struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','trainbfg', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000), 

    struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','trainrp', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000), 

     struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','trainscg', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000),

      struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','traincgb', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000),

      struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','traincgf', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000),

       struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','traincgp', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000),

   struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','trainoss', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000),

      struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','traingdx', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000),

    struct('nomeDataset','Train_Normalized', ...
        'hiddenLayers', [10], ...
        'transferFcn', {{'tansig', 'purelin'}}, ...
        'learningRate', 0.01, ...
        'trainFcn','traingdm', ...
        'trainRatio',0.75, ...
        'valRatio',0, ...
        'testRatio',0.15, ...
        'epochs',1000),
 };

for i=1:size(configs,1)
    config=configs(i);
    config=cell2mat(config);
    massTrain(N,config);
end
